import fs from "node:fs";
import path from "node:path";

const briefsDir = path.join(process.cwd(), "content", "briefs");
const today = new Date().toISOString().slice(0, 10);
const outputPath = path.join(briefsDir, `${today}.json`);

function main() {
  if (!fs.existsSync(briefsDir)) {
    fs.mkdirSync(briefsDir, { recursive: true });
  }

  if (fs.existsSync(outputPath)) {
    console.log(`Brief already exists for ${today}: ${outputPath}`);
    return;
  }

  const template = {
    date: today,
    title: "Guy Daily Brief",
    summary: "Daily brief placeholder generated by the v1 pipeline stub.",
    sections: {
      us: [],
      world: [],
      tech: [],
    },
    watchlist: [],
  };

  fs.writeFileSync(outputPath, `${JSON.stringify(template, null, 2)}\n`, "utf8");
  console.log(`Created placeholder brief: ${outputPath}`);
}

main();
